version: '3.8'

services:
  flask-service:
    build:
      context: ../ml-moderation-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  spring-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - FLASK_URL=http://flask-service:5000/predict

networks:
  app-network:
    driver: bridge